### ISSUE TITLE
This is shit

### ISSUE THREAD

**Issue by maikka39** [Raymonzut/Personal-Website#4] opened 2020-05-11 19:09 UTC
https://github.com/Raymonzut/Personal-Website/blob/5c91c10bc076a406dc82bec18f1edee415351972/server/index.js#L10

**Comment by Raymonzut** [comment] 2020-05-11 19:10
Duplicate of #3

**Comment by maikka39** [comment] 2020-05-11 19:10
Sorry..

**Comment by maikka39** [comment] 2020-05-11 19:10
But you opened it because I told you

**Closed by Raymonzut** 2020-05-11 19:10 UTC

**Comment by Raymonzut** [comment] 2020-05-11 19:20
Thx for that!
